#!/usr/bin/env bash

set -ex

rm -rf exiftool_git
git clone https://github.com/exiftool/exiftool.git exiftool_git
rm -rf exiftool_git/.git
cd ./exiftool_git || exit
perl Makefile.PL
make
make test

cd ../
mkdir -p ./exiftool
cp -R ./exiftool_git/lib ./exiftool_git/exiftool ./exiftool
chmod +x ./exiftool/exiftool

rm -rf exiftool_git

echo "Exiftool updated successfully!"
EXIFTOOL_VERSION=$(./exiftool/exiftool -ver)

git branch "v${EXIFTOOL_VERSION}" main
git checkout "v${EXIFTOOL_VERSION}"
