#!/usr/bin/env bash

rm -rf exiftool_git
git clone https://github.com/exiftool/exiftool.git exiftool_git
rm -rf exiftool_git/.git
cd ./exiftool_git || exit
perl Makefile.PL
make
make test

cd ../
mkdir -p ./exiftool
cp -R ./exiftool_git/lib ./exiftool_git/exiftool ./exiftool
chmod +x ./exiftool/exiftool

rm -rf exiftool_git
VERSION=$(./exiftool/exiftool -ver)
echo "Version: ${VERSION}"
git checkout -b "v${VERSION}"
git add exiftool
git commit -m "Update exiftool to version ${VERSION}"
git push --set-upstream origin "v${VERSION}"

gh pr create --assignee woss --body "" --title "Update exiftool to version ${VERSION}"
