name: Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: generate release
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}